"""initial schema

Revision ID: 6c3892d688b3
Revises: 
Create Date: 2026-03-08 20:41:49.487165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c3892d688b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fee_pre_member_cents', sa.Integer(), nullable=True),
    sa.Column('fee_pre_general_cents', sa.Integer(), nullable=True),
    sa.Column('fee_late_cents', sa.Integer(), nullable=True),
    sa.Column('pre_entry_close_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_start_date'), ['start_date'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_trial_secretary', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('event_pdfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('governing_body', sa.String(length=10), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'governing_body', 'document_type', name='uq_event_pdf')
    )
    with op.batch_alter_table('event_pdfs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_pdfs_event_id'), ['event_id'], unique=False)

    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('membership_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_user_id'), ['user_id'], unique=False)

    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('dog_name', sa.String(length=255), nullable=False),
    sa.Column('pricing_tier', sa.String(length=20), nullable=False),
    sa.Column('fee_cents', sa.Integer(), nullable=False),
    sa.Column('paypal_order_id', sa.String(length=100), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_manual_entry', sa.Boolean(), nullable=False),
    sa.Column('verification_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paypal_order_id')
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registrations_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_user_id'), ['user_id'], unique=False)

    op.create_table('trial_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('handler_name', sa.String(length=255), nullable=False),
    sa.Column('handler_email', sa.String(length=255), nullable=False),
    sa.Column('handler_phone', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('dog_name', sa.String(length=255), nullable=False),
    sa.Column('dog_breed', sa.String(length=100), nullable=True),
    sa.Column('dog_registration_number', sa.String(length=100), nullable=True),
    sa.Column('total_fee_cents', sa.Integer(), nullable=False),
    sa.Column('paypal_order_id', sa.String(length=100), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_manual_entry', sa.Boolean(), nullable=False),
    sa.Column('verification_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paypal_order_id')
    )
    with op.batch_alter_table('trial_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trial_entries_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trial_entries_user_id'), ['user_id'], unique=False)

    op.create_table('trials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('governing_body', sa.String(length=10), nullable=False),
    sa.Column('akc_event_number', sa.String(length=50), nullable=True),
    sa.Column('reg_close_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fee_per_class_cents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trials_event_id'), ['event_id'], unique=False)

    op.create_table('trial_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trial_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trial_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trial_events_trial_id'), ['trial_id'], unique=False)

    op.create_table('trial_event_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trial_event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trial_event_id'], ['trial_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trial_event_classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trial_event_classes_trial_event_id'), ['trial_event_id'], unique=False)

    op.create_table('trial_entry_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trial_entry_id', sa.Integer(), nullable=False),
    sa.Column('trial_event_id', sa.Integer(), nullable=False),
    sa.Column('trial_event_class_id', sa.Integer(), nullable=False),
    sa.Column('call_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trial_entry_id'], ['trial_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trial_event_class_id'], ['trial_event_classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trial_event_id'], ['trial_events.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trial_entry_id', 'trial_event_id', name='uq_entry_event')
    )
    with op.batch_alter_table('trial_entry_selections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trial_entry_selections_trial_entry_id'), ['trial_entry_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trial_entry_selections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trial_entry_selections_trial_entry_id'))

    op.drop_table('trial_entry_selections')
    with op.batch_alter_table('trial_event_classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trial_event_classes_trial_event_id'))

    op.drop_table('trial_event_classes')
    with op.batch_alter_table('trial_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trial_events_trial_id'))

    op.drop_table('trial_events')
    with op.batch_alter_table('trials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trials_event_id'))

    op.drop_table('trials')
    with op.batch_alter_table('trial_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trial_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_trial_entries_event_id'))

    op.drop_table('trial_entries')
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_user_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_event_id'))

    op.drop_table('registrations')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_user_id'))

    op.drop_table('members')
    with op.batch_alter_table('event_pdfs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_pdfs_event_id'))

    op.drop_table('event_pdfs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_start_date'))

    op.drop_table('events')
    # ### end Alembic commands ###
